### ISSUE TITLE
[Meta] Proper excavator adoption

### ISSUE THREAD

**Issue by Ash258** [Ash258/scoop-Ash258#13]
- [ ] Create new identity
    - [ ] New collaborator with full access (`Scoop-Updater`)
    - [ ] Look for better adoption (best to not create new github user)
	    - [ ] Only bind new ssh key into project and use it for pushing
		- [ ] Generate new ssh identity on test VM
		- [ ] Add this key as Deploy key to repository
		- [ ] Test some branch creating and pushing
    - [ ] Push access
    - [ ] Add .ssh identity into server
- [ ] Finish server and Youtrack setup
- [ ] Setup Excavator
    - [ ] Default intervals❓❓
    - [ ] https://github.com/Ash258/scoop-Ash258/
    - [ ] https://github.com/Ash258/scoop-JetBrains/
- [ ] Setup Excavator
	- [ ] Best would be one huge docker-compose with Excavator, Youtrack and other needed containers
- [ ] Make logs available through some website, not only ftp / share
    - [ ] nginx
    - [ ] caddy

**Comment by Ash258** [comment]
This should be done in #14

**Comment by Ash258** [comment]
Closed in favor of #14, #31
